repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
  - repo: https://github.com/pazmivaniye/pre-commit-hooks
    rev: 9069d8304a237c3f7ef0da325ed5763c3681ba55
    hooks:
      - id: check-chars
      - id: check-filenames
      - id: check-line-length
      - id: check-python-quotes
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: Run static code analyzer
        entry: mypy
        language: system
        types:
          - python
        args:
          - --strict
          - --follow-untyped-imports
      - id: check-nanorc-files
        name: check nanorc files
        description: Check NanoRC files for consistency
        entry: ./check_nanorc.py
        language: system
        files: \.nanorc$
